name: Android CI (auto-detect, resilient)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Detect module, compileSdk, AGP→JDK, and build-tools
      - name: Detect Android project settings
        id: detect
        shell: bash
        run: |
          set -euo pipefail

          # 1) Find first module that applies com.android.application; fallback to 'app' or root
          APP_MODULE=$(grep -RIl --include='build.gradle*' 'com\.android\.application' . \
            | sed 's|^\./||; s|/build\.gradle.*$||' | sort | head -n1)
          if [[ -z "${APP_MODULE}" ]]; then
            if [[ -d app ]]; then APP_MODULE="app"; else APP_MODULE="."; fi
          fi

          # 2) Detect compileSdk/compileSdkVersion in Groovy or Kotlin DSL
          COMPILE_SDK=$(grep -Rho --include='build.gradle*' \
            -E 'compileSdk(Version)?\s*[=:]\s*[0-9]+' "${APP_MODULE}" 2>/dev/null \
            | grep -Eo '[0-9]+' | head -n1 || true)
          [[ -z "${COMPILE_SDK}" ]] && COMPILE_SDK=34

          # 3) Detect AGP version to choose JDK
          AGP=$(grep -Rho --include='build.gradle*' \
                -E 'com\.android\.tools\.build:gradle[: ]+[0-9]+\.[0-9]+(\.[0-9]+)?' . 2>/dev/null \
                | head -n1 | grep -Eo '[0-9]+\.[0-9]+(\.[0-9]+)?' || true)
          if [[ -z "${AGP}" && -f gradle/libs.versions.toml ]]; then
            AGP=$(grep -E 'agp[^=]*=' gradle/libs.versions.toml | grep -Eo '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -n1 || true)
          fi

          # 4) Decide JDK: AGP >= 8.5 → JDK 21, else 17
          JDK_VER=17
          if [[ -n "${AGP}" ]]; then
            AGP_MAJOR=$(cut -d. -f1 <<<"$AGP"); AGP_MINOR=$(cut -d. -f2 <<<"$AGP")
            if (( AGP_MAJOR > 8 )) || (( AGP_MAJOR == 8 && AGP_MINOR >= 5 )); then JDK_VER=21; fi
          fi

          # 5) Pair build-tools with compileSdk (best-effort)
          case "${COMPILE_SDK}" in
            35) BUILD_TOOLS="35.0.0" ;;
            34) BUILD_TOOLS="34.0.0" ;;
            *)  BUILD_TOOLS="34.0.0" ;;
          esac

          {
            echo "app_module=${APP_MODULE}"
            echo "compile_sdk=${COMPILE_SDK}"
            echo "build_tools=${BUILD_TOOLS}"
            echo "jdk=${JDK_VER}"
            echo "agp=${AGP:-unknown}"
          } >> "$GITHUB_OUTPUT"

          echo "Detected:"
          echo "  APP_MODULE=${APP_MODULE}"
          echo "  COMPILE_SDK=${COMPILE_SDK}"
          echo "  BUILD_TOOLS=${BUILD_TOOLS}"
          echo "  AGP=${AGP:-unknown}"
          echo "  JDK=${JDK_VER}"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ steps.detect.outputs.jdk }}
          cache: gradle

      # Install Google cmdline-tools directly (avoid action parsing issues)
      - name: Install Android cmdline-tools (latest)
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"
          cd "${ANDROID_SDK_ROOT}/cmdline-tools"
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip
          rm cmdline-tools.zip
          # Ensure stable path at .../cmdline-tools/latest
          if [ -d "cmdline-tools" ]; then mv cmdline-tools latest; fi
          echo "Installed to ${ANDROID_SDK_ROOT}/cmdline-tools/latest"

      # Accept licenses WITHOUT pipefail so 'yes' won't break the job
      - name: Accept SDK licenses
        shell: bash
        run: |
          set -e
          yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --sdk_root="${ANDROID_SDK_ROOT}" --licenses >/dev/null 2>&1 || true

      # Install SDK packages (no 'yes' pipe; use --install per package)
      - name: Install required SDK packages
        shell: bash
        run: |
          set -euxo pipefail
          SDKM="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"
          "$SDKM" --sdk_root="${ANDROID_SDK_ROOT}" --install "platform-tools"
          "$SDKM" --sdk_root="${ANDROID_SDK_ROOT}" --install "platforms;android-${{ steps.detect.outputs.compile_sdk }}"
          "$SDKM" --sdk_root="${ANDROID_SDK_ROOT}" --install "build-tools;${{ steps.detect.outputs.build_tools }}"

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: |
            ${{ steps.detect.outputs.app_module }}/build/outputs/**/apk/debug/*-debug.apk
            app/build/outputs/**/apk/debug/*-debug.apk
            */build/outputs/**/apk/debug/*-debug.apk

      # If anything fails, dump quick SDK diagnostics
      - name: Diagnose SDK (on failure)
        if: failure()
        run: |
          echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}"
          ls -la "${ANDROID_SDK_ROOT}/cmdline-tools" || true
          ls -la "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin" || true
          "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --list | head -n 200 || true
