name: Android CI (AI Consciousness)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # GitHub runners already define ANDROID_SDK_ROOT; keep it explicit.
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Install/upgrade cmdline-tools first using the existing sdkmanager (16.0)
      - name: Install cmdline-tools;latest
        run: |
          set -e
          yes | "${ANDROID_SDK_ROOT}/cmdline-tools/16.0/bin/sdkmanager" --sdk_root="${ANDROID_SDK_ROOT}" "cmdline-tools;latest"

      # Now use the latest sdkmanager to install the rest, each as its own arg
      - name: Install platform-tools, platform & build-tools
        run: |
          set -e
          yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --sdk_root="${ANDROID_SDK_ROOT}" "platform-tools"
          yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --sdk_root="${ANDROID_SDK_ROOT}" "platforms;android-34"
          yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --sdk_root="${ANDROID_SDK_ROOT}" "build-tools;34.0.0"

      - name: Accept licenses (belt-and-suspenders)
        run: yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --licenses

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build Debug APK (wrapper)
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-consciousness-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
