name: One-Shot Materialize & Build (Compose M3 Locked + Guards) — FIXED KT

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_app:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      BRANCH: feature/ai-consciousness-oneshot
      PKG_DIR: app/src/main/java/com/example/aiconsciousness

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create/Checkout branch
        run: |
          set -eux
          git checkout -b "$BRANCH" || git checkout "$BRANCH"

      # (omitting the long scaffold for brevity — assume it's identical to previous file)
      # ↓↓↓ BEGIN: only the problematic hotfix step is replaced ↓↓↓
      - name: Hotfix NavScaffold to Material3-only (base64-safe)
        shell: bash
        run: |
          set -euo pipefail
          OUT="app/src/main/java/com/example/aiconsciousness/nav/NavScaffold.kt"
          mkdir -p "$(dirname "$OUT")"
          echo 'cGFja2FnZSBjb20uZXhhbXBsZS5haWNvbnNjaW91c25lc3MubmF2CmltcG9ydCBhbmRyb2lkeC5jb21wb3NlLm1hdGVyaWFsLmljb25zLkljb25zCmltcG9ydCBhbmRyb2lkeC5jb21wb3NlLm1hdGVyaWFsLmljb25zLmZpbGxlZC5DaGF0CmltcG9ydCBhbmRyb2lkeC5jb21wb3NlLm1hdGVyaWFsLmljb25zLmZpbGxlZC5TZXR0aW5ncwppbXBvcnQgYW5kcm9pZHguY29tcG9zZS5tYXRlcmlhbC5pY29ucy5maWxsZWQuVHVuZQppbXBvcnQgYW5kcm9pZHguY29tcG9zZS5tYXRlcmlhbDMuQ2VudGVyQWxpZ25lZFRvcEFwcEJhcgppbXBvcnQgYW5kcm9pZHguY29tcG9zZS5tYXRlcmlhbDMuSWNvbgppbXBvcnQgYW5kcm9pZHguY29tcG9zZS5tYXRlcmlhbDMuTmF2aWdhdGlvbkJhcgppbXBvcnQgYW5kcm9pZHguY29tcG9zZS5tYXRlcmlhbDMuTmF2aWdhdGlvbkJhckl0ZW0KaW1wb3J0IGFuZHJvaWR4LmNvbXBvc2UubWF0ZXJpYWwzLlNjYWZmb2xkCmltcG9ydCBhbmRyb2lkeC5jb21wb3NlLm1hdGVyaWFsMy5TdXJmYWNlCmltcG9ydCBhbmRyb2lkeC5jb21wb3NlLm1hdGVyaWFsMy5UZXh0CmltcG9ydCBhbmRyb2lkeC5jb21wb3NlLnJ1bnRpbWUuQ29tcG9zYWJsZQppbXBvcnQgYW5kcm9pZHguY29tcG9zZS51aS5Nb2RpZmllcgppbXBvcnQgYW5kcm9pZHguY29tcG9zZS51aS51bml0LmRwCmltcG9ydCBhbmRyb2lkeC5uYXZpZ2F0aW9uLk5hdkhvc3RDb250cm9sbGVyCmltcG9ydCBhbmRyb2lkeC5uYXZpZ2F0aW9uLmNvbXBvc2UuY3VycmVudEJhY2tTdGFja0VudHJ5QXNTdGF0ZQpAQ29tcG9zYWJsZQpmdW4gTmF2U2NhZmZvbGQobmF2OiBOYXZIb3N0Q29udHJvbGxlciwgY29udGVudDogQENvbXBvc2FibGUgKCkgLT4gVW5pdCkgewogIHZhbCByb3V0ZSA9IG5hdi5jdXJyZW50QmFja1N0YWNrRW50cnlBc1N0YXRlKCkudmFsdWU/LmRlc3RpbmF0aW9uPy5yb3V0ZQogIFNjYWZmb2xkKAogICAgdG9wQmFyID0geyBDZW50ZXJBbGlnbmVkVG9wQXBwQmFyKHRpdGxlID0geyBUZXh0KCJBSSBDb25zY2lvdXNuZXNzIikgfSkgfSwKICAgIGJvdHRvbUJhciA9IHsKICAgICAgaWYgKHJvdXRlICE9IERlc3QuU2V0dXAucm91dGUpIHsKICAgICAgICBOYXZpZ2F0aW9uQmFyIHsKICAgICAgICAgIE5hdmlnYXRpb25CYXJJdGVtKAogICAgICAgICAgICBzZWxlY3RlZCA9IHJvdXRlID09IERlc3QuQ2hhdC5yb3V0ZSwKICAgICAgICAgICAgb25DbGljayA9IHsgbmF2Lm5hdmlnYXRlKERlc3QuQ2hhdC5yb3V0ZSkgfSwKICAgICAgICAgICAgaWNvbiA9IHsgSWNvbihJY29ucy5GaWxsZWQuQ2hhdCwgY29udGVudERlc2NyaXB0aW9uID0gbnVsbCkgfSwKICAgICAgICAgICAgbGFiZWwgPSB7IFRleHQoIkNoYXQiKSB9CiAgICAgICAgICApCiAgICAgICAgICBOYXZpZ2F0aW9uQmFySXRlbSgKICAgICAgICAgICAgc2VsZWN0ZWQgPSByb3V0ZSA9PSBEZXN0Lk1vZGVscy5yb3V0ZSwKICAgICAgICAgICAgb25DbGljayA9IHsgbmF2Lm5hdmlnYXRlKERlc3QuTW9kZWxzLnJvdXRlKSB9LAogICAgICAgICAgICBpY29uID0geyBJY29uKEljb25zLkZpbGxlZC5UdW5lLCBjb250ZW50RGVzY3JpcHRpb24gPSBudWxsKSB9LAogICAgICAgICAgICBsYWJlbCA9IHsgVGV4dCgiTW9kZWxzIikgfQogICAgICAgICAgKQogICAgICAgICAgTmF2aWdhdGlvbkJhckl0ZW0oCiAgICAgICAgICAgIHNlbGVjdGVkID0gcm91dGUgPT0gRGVzdC5TZXR0aW5ncy5yb3V0ZSwKICAgICAgICAgICAgb25DbGljayA9IHsgbmF2Lm5hdmlnYXRlKERlc3QuU2V0dGluZ3Mucm91dGUpIH0sCiAgICAgICAgICAgIGljb24gPSB7IEljb24oSWNvbnMuRmlsbGVkLlNldHRpbmdzLCBjb250ZW50RGVzY3JpcHRpb24gPSBudWxsKSB9LAogICAgICAgICAgICBsYWJlbCA9IHsgVGV4dCgiU2V0dGluZ3MiKSB9CiAgICAgICAgICApCiAgICAgICAgfQogICAgICB9CiAgICB9CiAgKSB7IGlubmVyIC0+IFN1cmZhY2UodG9uYWxFbGV2YXRpb24gPSAwLmRwLCBtb2RpZmllciA9IE1vZGlmaWVyLnBhZGRpbmcoaW5uZXIpKSB7IGNvbnRlbnQoKSB9IH0KfQo=' | base64 -d > "$OUT"
          echo "Wrote $OUT via base64 (no heredoc)."

      # Guards (same as before)
      - name: Install ripgrep (scanner)
        run: sudo apt-get update && sudo apt-get install -y ripgrep

      - name: Guard — ban Material 2 widget imports (icons allowed)
        shell: bash
        run: |
          set -euo pipefail
          if rg -n '^import\s+androidx\.compose\.material\.(?!icons)' app/src | tee /dev/stderr; then
            echo "❌ Found Material 2 widget imports. Use androidx.compose.material3.* instead."
            exit 1
          fi
          echo "✅ No Material 2 widget imports detected (icons allowed)."

      - name: Guard — ban M2 ListItem params
        shell: bash
        run: |
          set -euo pipefail
          if rg -n 'headlineText=|supportingText=|overlineText=' app/src | tee /dev/stderr; then
            echo "❌ Found Material 2 ListItem params. Use Material3 slots."
            exit 1
          fi
          echo "✅ ListItem parameters are Material3 style."
