name: Patch — Providers.kt via base64 (Python writer, YAML-proof)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  patch_providers_b64_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write Providers.kt using Python base64 decode
        shell: bash
        run: |
          set -euo pipefail
          python3 - <<'PY'
import base64, os
b64_content = """cGFja2FnZSBjb20uZXhhbXBsZS5haWNvbnNjaW91c25lc3MuZGF0YQoKaW1wb3J0IG9yZy5qc29uLkpTT05BcnJheQppbXBvcnQgb3JnLmpzb24uSlNPTk9iamVjdAppbXBvcnQgamF2YS5pby5CdWZmZXJlZFJlYWRlcgppbXBvcnQgamF2YS5uZXQuSHR0cFVSTENvbm5lY3Rpb24KaW1wb3J0IGphdmEubmV0LlVSTAoKZW51bSBjbGFzcyBQcm92aWRlcklkKHZhbCBsYWJlbDogU3RyaW5nKSB7IFVTRVIoIllvdSIpLCBPUEVOQUkoIk9wZW5BSSIpLCBBTlRIUk9QSUMoIkNsYXVkZSIpLCBHRU1JTkkoIkdlbWluaSIpLCBHUk9LKCJHcm9rIikgfQoKZGF0YSBjbGFzcyBDaGF0TWVzc2FnZSh2YWwgZnJvbTogU3RyaW5nLCB2YWwgdGV4dDogU3RyaW5nL...
path = "app/src/main/java/com/example/aiconsciousness/data/Providers.kt"
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, "wb") as f:
    f.write(base64.b64decode(b64_content))
print("Wrote", path)
PY

      - name: Commit & push Providers.kt
        shell: bash
        run: |
          set -eux
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No changes after patch."
          else
            git add app/src/main/java/com/example/aiconsciousness/data/Providers.kt
            git commit -m "Patch: write Providers.kt via Python/base64 (YAML-proof)"
            git push
          fi
