name: Patch — Providers.kt via base64 (clean heredoc)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  patch_providers_b64_clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write Providers.kt using Python base64 decode
        run: |
          set -euo pipefail
          python3 - <<'PY'
import base64, os

b64_content = """cGFja2FnZSBjb20uZXhhbXBsZS5haWNvbnNjaW91c25lc3MuZGF0YQoK...<rest of base64>..."""

path = "app/src/main/java/com/example/aiconsciousness/data/Providers.kt"
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, "wb") as f:
    f.write(base64.b64decode(b64_content))
print("Wrote", path)
PY

      - name: Commit & push Providers.kt
        run: |
          set -eux
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No changes after patch."
          else
            git add app/src/main/java/com/example/aiconsciousness/data/Providers.kt
            git commit -m "Patch: write Providers.kt via Python/base64 (clean heredoc)"
            git push
          fi
